# Generated by Django 2.1.3 on 2019-06-20 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toshokan', '0005_auto_20190620_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficult_kanji', models.ManyToManyField(related_name='difficult_kanji', to='toshokan.Kanji')),
                ('interesting_kanji', models.ManyToManyField(related_name='interesting_kanji', to='toshokan.Kanji')),
                ('known_kanji', models.ManyToManyField(related_name='known_kanji', to='toshokan.Kanji')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
