# Generated by Django 2.1.3 on 2019-06-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='difficult_kanji',
            field=models.ManyToManyField(blank=True, related_name='difficult_kanji', to='toshokan.Kanji'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interesting_kanji',
            field=models.ManyToManyField(blank=True, related_name='interesting_kanji', to='toshokan.Kanji'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='known_kanji',
            field=models.ManyToManyField(blank=True, related_name='known_kanji', to='toshokan.Kanji'),
        ),
    ]
