# Generated by Django 2.1.3 on 2019-06-21 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0006_kanjicompound'),
        ('base', '0002_auto_20190620_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toshokan.Kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.UserProfile')),
            ],
        ),
    ]
