# Generated by Django 2.1.3 on 2019-06-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_kanjicomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjicomment',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_comment', to='toshokan.Kanji'),
        ),
    ]
