# Generated by Django 2.1.3 on 2019-06-21 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190621_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjicomment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kanjicomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='base.UserProfile'),
        ),
    ]
