# Generated by Django 2.2.2 on 2019-07-11 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0010_auto_20190709_2219'),
        ('base', '0006_auto_20190623_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_group', to='base.KanjiGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='base.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiReviewObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji', to='toshokan.Kanji')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='base.KanjiReview')),
            ],
        ),
    ]
