# Generated by Django 2.2.2 on 2019-07-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_kanjireview_kanjireviewobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiReviewObjectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_response', models.CharField(max_length=500)),
                ('response_correct', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_option', to='base.KanjiReviewObject')),
            ],
        ),
    ]
