# Generated by Django 2.2.2 on 2019-07-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_kanjireviewobjectoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjireviewobjectoption',
            name='review',
        ),
        migrations.AddField(
            model_name='kanjireviewobjectoption',
            name='review_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='base.KanjiReviewObject'),
        ),
        migrations.AlterField(
            model_name='kanjireview',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.KanjiGroup'),
        ),
        migrations.AlterField(
            model_name='kanjireview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.UserProfile'),
        ),
        migrations.AlterField(
            model_name='kanjireviewobject',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_objects', to='toshokan.Kanji'),
        ),
        migrations.AlterField(
            model_name='kanjireviewobject',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_objects', to='base.KanjiReview'),
        ),
    ]
