# Generated by Django 2.2.2 on 2019-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_kanjireviewobject_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjireviewobjectoption',
            name='response_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
