# Generated by Django 2.2.2 on 2019-07-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_kanjireviewobjectoption_response_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjireview',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
