# Generated by Django 2.1.3 on 2019-05-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('alt_characters', models.CharField(max_length=10)),
                ('radical', models.CharField(max_length=10)),
                ('strokes', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('meaning', models.TextField()),
                ('reading_jpn', models.CharField(max_length=100)),
                ('reading_eng', models.CharField(max_length=100)),
            ],
        ),
    ]
