# Generated by Django 2.1.3 on 2019-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0003_auto_20190612_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mastered_kanji',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='known_kanji',
            field=models.ManyToManyField(related_name='known_kanji', to='toshokan.Kanji'),
        ),
    ]
