# Generated by Django 2.1.3 on 2019-06-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0004_auto_20190613_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='difficult_kanji',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interesting_kanji',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='known_kanji',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
