# Generated by Django 2.1.3 on 2019-06-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0005_auto_20190620_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.CharField(max_length=20)),
                ('meaning', models.TextField()),
                ('reading_jpn', models.CharField(max_length=100)),
                ('reading_eng', models.CharField(max_length=100)),
                ('references', models.ManyToManyField(blank=True, related_name='constituent_kanji', to='toshokan.Kanji')),
            ],
        ),
    ]
