# Generated by Django 2.2.2 on 2019-07-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0006_kanjicompound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjicompound',
            name='references',
        ),
        migrations.CreateModel(
            name='KanjiCompoundElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toshokan.Kanji')),
                ('kanji_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toshokan.KanjiCompound')),
            ],
        ),
        migrations.AddField(
            model_name='kanjicompound',
            name='constituent_kanji',
            field=models.ManyToManyField(blank=True, related_name='constituent_kanji', through='toshokan.KanjiCompoundElement', to='toshokan.Kanji'),
        ),
    ]
