# Generated by Django 2.2.2 on 2019-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokan', '0008_remove_kanjicompound_reading_jpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjicompound',
            name='frequency',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
